; SPDX-License-Identifier: GPL-3.0-or-later
; Qt Quick Controls configuration (read from :/qtquickcontrols2.conf).
; Basic on all three OSes: the style Qt designs for full customisation. The
; app's own controls (qml/RowPlay: PushButton, ToolbarButton, …) replace its
; visuals, and Main.qml sets the whole palette from Theme.qml so any stock
; control left inherits the design system's colours (ADR 0013). qtbridge
; exposes no QQuickStyle binding, so the style is forced through this file.
[Controls]
Style=Basic
