; SPDX-License-Identifier: GPL-3.0-or-later
; Qt Quick Controls configuration (read from :/qtquickcontrols2.conf through
; a QFileSelector, so a platform's variant beside it takes precedence).
; No style here: macOS gets the macOS style and Linux Fusion, Qt's defaults
; (ADR 0015). This file exists for the selector to find the Windows variant,
; qml/+windows/qtquickcontrols2.conf, which Qt reads only when this one
; exists (QQuickStylePrivate::settings).
[Controls]
