; SPDX-License-Identifier: GPL-3.0-or-later
; Qt Quick Controls configuration (read from :/qtquickcontrols2.conf).
; Fusion on all three OSes, coloured from Theme.qml (ADR: no Qt Widgets,
; consistent cross-platform look). qtbridge exposes no QQuickStyle binding,
; so the style is forced through this file instead.
[Controls]
Style=Fusion
