; SPDX-License-Identifier: GPL-3.0-or-later
; Windows: FluentWinUI3 (ADR 0015, decision 1 as amended). Qt's default there,
; the Windows style, draws its controls light under the dark scheme, so the
; scheme's light text on them was unreadable in CI's captures; FluentWinUI3
; draws both schemes. QT_QUICK_CONTROLS_STYLE still overrides this file.
[Controls]
Style=FluentWinUI3
