#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Vendor the baked venue assets into assets/replay/venues/.

Unlike `vendor-replay-assets.py`, the venues have no upstream artifact to
verify against: they are generated by `tools/bake-venues/bake.sh` from the
pinned rowplay checkout, so "reviewed" means the manifest written here.

Workflow:

    tools/bake-venues/bake.sh --verify          # reproducible bake
    tools/vendor-venues.py --accept             # review the hashes, install
    tools/vendor-venues.py --emit-rust          # refresh asset_hashes.rs

Without `--accept` the script verifies the staging directory byte for byte
against the committed `venues/MANIFEST.json` (size + SHA-256 per file) and
refuses to install anything that differs — so an asset change is always an
explicit, reviewed act with its own diff. The manifest is written from the
staging directory only when the reviewed hashes change.
"""

import argparse
import hashlib
import json
import shutil
import sys
from pathlib import Path

# The rowplay code commit the baker reads; must match bake.mjs's pin and the
# pinned reference in docs/source-map.md.
UPSTREAM_COMMIT = "011e8303b66b4d2265a6f1ec8b3ed9d8ed497086"

MANIFEST_NAME = "MANIFEST.json"

# The vendored subtrees and the generated/doc files that carry no hash pin.
UNPINNED = [MANIFEST_NAME, "README.md"]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def staging_files(staging: Path) -> list[Path]:
    files = []
    for path in sorted(staging.rglob("*")):
        if path.is_file():
            files.append(path)
    return files


def build_manifest(staging: Path) -> dict:
    entries = []
    for path in staging_files(staging):
        rel = path.relative_to(staging).as_posix()
        entries.append({"path": rel, "bytes": path.stat().st_size, "sha256": sha256(path)})
    entries.sort(key=lambda entry: entry["path"])
    return {"format": 1, "generatedBy": "tools/bake-venues/bake.sh", "upstreamCommit": UPSTREAM_COMMIT, "files": entries}


def read_manifest(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def verify(staging: Path, manifest: dict) -> None:
    expected = {entry["path"]: entry for entry in manifest["files"]}
    present = {}
    for path in staging_files(staging):
        rel = path.relative_to(staging).as_posix()
        present[rel] = {"bytes": path.stat().st_size, "sha256": sha256(path)}
    missing = sorted(set(expected) - set(present))
    extra = sorted(set(present) - set(expected))
    if missing:
        sys.exit(f"staging is missing files the manifest pins: {missing}")
    if extra:
        sys.exit(f"staging has files the manifest does not pin: {extra} (re-run with --accept to review)")
    for rel, entry in sorted(expected.items()):
        actual = present[rel]
        if actual["bytes"] != entry["bytes"] or actual["sha256"] != entry["sha256"]:
            sys.exit(
                f"{rel}: staged bytes differ from the reviewed manifest "
                f"({actual['bytes']} B / {actual['sha256'][:12]} vs "
                f"{entry['bytes']} B / {entry['sha256'][:12]}); "
                "re-bake and re-review with --accept"
            )
    print(f"staging matches the reviewed manifest ({len(expected)} files)")


def licence_for(rel: str) -> str:
    if rel.endswith(".glb") or rel.startswith("procedural/"):
        return "MIT (rowplay, generated)"
    if rel.endswith(".json"):
        return "MIT (rowplay, generated contract)"
    return "MIT (rowplay, generated)"


def source_note(rel: str) -> str:
    if rel.endswith(".glb"):
        return "`tools/bake-venues/bake.mjs` over `src/lib/replay/renderer3dEnvironment.ts`"
    if rel.endswith(".json"):
        return "`tools/bake-venues/bake.mjs` (contract sidecar)"
    return "`tools/bake-venues/bake.mjs` procedural map encoder"


def provenance_rows(manifest: dict) -> str:
    lines = []
    for entry in manifest["files"]:
        rel = entry["path"]
        lines.append(
            f"| `assets/replay/venues/{rel}` | rowplay (generated) | "
            f"{source_note(rel)} | `{UPSTREAM_COMMIT[:12]}` | "
            f"`{entry['sha256']}` | {licence_for(rel)} ({entry['bytes']} B) |"
        )
    return "\n".join(lines)


def rewrite_provenance(repo_root: Path, rows: str) -> None:
    path = repo_root / "ASSET_PROVENANCE.md"
    text = path.read_text(encoding="utf-8")
    marker = "## Baked venues (generated)"
    if marker in text:
        head, _, rest = text.partition(marker)
        _, _, tail = rest.partition("## Reference sources (not vendored)")
        text = head + marker + "\n\n" + rest[: len(rest) - len(tail)]
    body = (
        marker
        + "\n\n"
        "The venue `.glb` files are baked from the pinned rowplay checkout by "
        "`tools/bake-venues/bake.sh` (ADR 0005, ADR 0010) and installed by "
        "`tools/vendor-venues.py`. Each `.glb` is accompanied by a contract "
        "JSON describing its materials, tier texture bindings and per-instance "
        "transforms; the spatial maps under `procedural/` are the web "
        "builder's water and snow DataTextures encoded to PNG. The bake is "
        "seeded (`20260913`) and byte-reproducible; the hashes below are "
        "asserted by `crates/rowplay-app/tests/asset_hashes.rs`.\n\n"
        "| Asset | Source repository | Source | Commit | SHA-256 | Licence |\n"
        "| --- | --- | --- | --- | --- | --- |\n"
        + rows
        + "\n\n"
    )
    tail_marker = "## Reference sources (not vendored)"
    if tail_marker in text:
        head, _, tail = text.partition(tail_marker)
        text = head + body + tail_marker + tail
    else:
        text = text.rstrip() + "\n\n" + body
    path.write_text(text, encoding="utf-8")


def emit_rust(manifest: dict) -> None:
    print("\n// Venue rows for crates/rowplay-app/tests/asset_hashes.rs:")
    for entry in manifest["files"]:
        print(f'    ("venues/{entry["path"]}", {entry["bytes"]}, "{entry["sha256"]}"),')


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--staging", type=Path, default=None, help="bake output (default: build/venues-staging)")
    parser.add_argument("--accept", action="store_true", help="write a fresh manifest from the staged bytes")
    parser.add_argument("--emit-rust", action="store_true", help="print the asset_hashes.rs rows")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    staging = args.staging or repo_root / "build" / "venues-staging"
    if not staging.is_dir():
        sys.exit(f"no staged venues at {staging}; run tools/bake-venues/bake.sh first")

    target = repo_root / "assets" / "replay" / "venues"
    target.mkdir(parents=True, exist_ok=True)
    manifest_path = target / MANIFEST_NAME

    if args.accept:
        manifest = build_manifest(staging)
        if manifest_path.is_file():
            previous = read_manifest(manifest_path)
            old = {entry["path"]: entry for entry in previous["files"]}
            new = {entry["path"]: entry for entry in manifest["files"]}
            added = sorted(set(new) - set(old))
            removed = sorted(set(old) - set(new))
            modified = sorted(
                rel for rel in set(old) & set(new) if old[rel]["sha256"] != new[rel]["sha256"]
            )
            print(f"manifest change: +{len(added)} -{len(removed)} ~{len(modified)}")
            for rel in added:
                print(f"  added    {rel}")
            for rel in removed:
                print(f"  removed  {rel}")
            for rel in modified:
                print(f"  modified {rel}")
        manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    else:
        if not manifest_path.is_file():
            sys.exit(f"no reviewed manifest at {manifest_path}; review a bake with --accept")
        manifest = read_manifest(manifest_path)
        verify(staging, manifest)

    # Install the pinned bytes, plus the unpinned docs.
    installed = 0
    for entry in manifest["files"]:
        source = staging / entry["path"]
        destination = target / entry["path"]
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, destination)
        installed += 1
    # Drop files the manifest no longer pins (e.g. a removed variant).
    pinned = {entry["path"] for entry in manifest["files"]}
    for path in sorted(target.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(target).as_posix()
        if rel not in pinned and rel not in UNPINNED:
            path.unlink()
            print(f"  removed stale {rel}")

    rewrite_provenance(repo_root, provenance_rows(manifest))
    print(f"vendored {installed} venue files; ASSET_PROVENANCE.md updated")
    if args.emit_rust:
        emit_rust(manifest)


if __name__ == "__main__":
    main()
